GET http://localhost:3001/

###
GET http://localhost:3001/api/notes

###

GET http://localhost:3001/api/notes/2

###

POST http://localhost:3001/api/notes
content-type: application/json

{
    "content": "I have the high ground"
}
###

DELETE  http://localhost:3001/api/notes/623476c7f87d1c92b6d69e04

###