GET http://localhost:3001/

###
GET http://localhost:3001/api/users

###

GET http://localhost:3001/api/notes/2

###

POST http://localhost:3001/api/login
content-type: application/json

{
    "email": "test@test.com",
    "password": "test"
}
###

DELETE  http://localhost:3001/api/notes/623476c7f87d1c92b6d69e04

###